# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20170513_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystatus',
            name='currency_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currencystatus',
            name='provider_id',
            field=models.IntegerField(),
        ),
    ]
