# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20170514_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystatus',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencystatus',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
